// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD6FPot8VxNlRHwp7onqIo3vWXz40SW4k',
    appId: '1:323956510203:web:2d15bca8e0b70702678f5e',
    messagingSenderId: '323956510203',
    projectId: 'learn-flutter-94fae',
    authDomain: 'learn-flutter-94fae.firebaseapp.com',
    storageBucket: 'learn-flutter-94fae.firebasestorage.app',
    measurementId: 'G-W2873FB8YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5IzW0AyaUHqorQYn0y1qbtr1fkw_wY8',
    appId: '1:323956510203:android:759c4638d02cfd61678f5e',
    messagingSenderId: '323956510203',
    projectId: 'learn-flutter-94fae',
    storageBucket: 'learn-flutter-94fae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACdR3h_8RDkmuEjBSQr5gfBPXD_wd6c5o',
    appId: '1:323956510203:ios:ee41914f9385c82a678f5e',
    messagingSenderId: '323956510203',
    projectId: 'learn-flutter-94fae',
    storageBucket: 'learn-flutter-94fae.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACdR3h_8RDkmuEjBSQr5gfBPXD_wd6c5o',
    appId: '1:323956510203:ios:ee41914f9385c82a678f5e',
    messagingSenderId: '323956510203',
    projectId: 'learn-flutter-94fae',
    storageBucket: 'learn-flutter-94fae.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD6FPot8VxNlRHwp7onqIo3vWXz40SW4k',
    appId: '1:323956510203:web:3b71bbef52e7f4a7678f5e',
    messagingSenderId: '323956510203',
    projectId: 'learn-flutter-94fae',
    authDomain: 'learn-flutter-94fae.firebaseapp.com',
    storageBucket: 'learn-flutter-94fae.firebasestorage.app',
    measurementId: 'G-2RM4R2S29P',
  );

}